### ISSUE TITLE
Add `ShimmerEVM` Test Network

### ISSUE THREAD

**Issue by antonionardella** [pcaversaccio/hardhat-project-template-ts#47]
### Describe the desired feature:

Shimmer launched the ShimmerEVM testnet. A L2 blockchain with a L1 DAG chain.

More information here:
[https://blog.shimmer.network/shimmerevm-testnet-launch/](https://blog.shimmer.network/shimmerevm-testnet-launch/)

I would like to add the ShimmerEVM testnet support to the project

Thank you

### Code example that solves the feature:

I already added the necessary information to my fork which is available here:

https://github.com/pcaversaccio/hardhat-project-template-ts/compare/main...antonionardella:hardhat-project-template-ts:main

**Comment by pcaversaccio** [comment]
Wanna pr :)?
